### ISSUE TITLE
Edit Entry in Edit Database

### ISSUE THREAD

**Issue by gelolacuesta** [ReinDC/CSSWENG-AY.24-25#1]
- The "Save Changes" button does not work yet.
- The "Cancel" button does not work yet. 
![image_2024-11-16_104024270](https://github.com/user-attachments/assets/da231169-fbcc-4cdc-977e-ea34b0faf26c)
- The delete button does not work yet.

**Comment by Blitz1r** [comment]
Delete Button removed. Save and Cancel button is now working
