### ISSUE TITLE
Forms (Pickup and Departure date)

### ISSUE THREAD

**Issue by gelolacuesta** [ReinDC/CSSWENG-AY.24-25#3]
Any year gets accepted. Pickup date should at least be greater than the date of booking.
![image](https://github.com/user-attachments/assets/9944800e-bc82-4189-ba0e-4b04e069e057)

**Comment by ReinDC** [comment]
Year is now locked into the current year and the subsequent years. Pickup date is now locked for the next day of the booking.
Departure date is now locked after the pickup date is chosen 

![image](https://github.com/user-attachments/assets/5c720de2-4b49-492f-841d-ae90b3fbd56d)

![image](https://github.com/user-attachments/assets/ac038adf-945e-46a3-97e2-18c75004ff1f)
