### ISSUE TITLE
Search function in database

### ISSUE THREAD

**Issue by gelolacuesta** [ReinDC/CSSWENG-AY.24-25#6]
When using the date filters From and To, when you click the filter button, it will go to a new page and say there is a server error.

![image](https://github.com/user-attachments/assets/464ade40-49d8-4dbb-baa7-2521d284bd6a)

![image](https://github.com/user-attachments/assets/db41265a-5796-40b9-a5bc-9fbdbd78706a)

**Comment by Blitz1r** [comment]
Date filter fixed
